title: Maison Rivage
description: Un authentique restaurant de cuisine gastronomique provençale ravissant le palais des amateurs comme des spécialistes !

url: "https://orionprojectcyber-crypto.github.io"
baseurl: "/maison-rivage"

remote_theme: biomadeira/jasper-theme

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
